name: Pull and Push Docker Images to ECR 

on:
  push:
    branches:
      - main

jobs:
  docker-sync:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_WORKING_DIR: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init -reconfigure
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -reconfigure

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan 

      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve -input=false

      - name: Get ECR URL
        id: ecr
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          REPO_URL=$(terraform output -raw demo_repo_url)
          echo "repo=$REPO_URL" >> $GITHUB_OUTPUT
          echo "registry=$(echo $REPO_URL | cut -d'/' -f1)" >> $GITHUB_OUTPUT

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin ${{ steps.ecr.outputs.registry }}

      - name: Pull and Push Docker Images
        run: |
          while IFS=: read -r image tag; do
            echo "Processing $image:$tag"
            ecr_repo="${{ steps.ecr.outputs.repo }}"
            docker pull "$image:$tag"
            docker tag "$image:$tag" "$ecr_repo:$tag"
            docker push "$ecr_repo:$tag"
          done < images.txt
